language: node_js
node_js:
  - '7'
script:
  - npm run test
before_install:
  - openssl aes-256-cbc -K $encrypted_2c456f34f8c3_key -iv $encrypted_2c456f34f8c3_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 120.25.217.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production
  - tar -jcf cache.tar.bz2 *
  - scp cache.tar.bz2 root@120.25.217.56:~/
  - ssh root@120.25.217.56 'rm -rf ~/MicroServer/User'
  - ssh root@120.25.217.56 'mkdir -p User && tar -jxf cache.tar.bz2 -C User'
  - ssh root@120.25.217.56 'mv User ~/MicroServer/ && pm2 startOrReload ~/MicroServer/User/pm2.json'

