#!/bin/bash
#自动部署脚本
#travis ci 自动部署

msg='deploy'
if [ "--m"x == "$1"x -o  "-m"x == "$1"x  -o  "\"--m\""x == "$1"x  -o  "\"-m\""x == "$1"x ] && [ $# -ge 2 ];
then  
    msg=${@:2}
fi  

echo 'git add start'

git add *
git add -A

msg=\'$msg\'

echo 'git add end'
echo 'git commit start'
echo $msg

git commit -m $msg

echo 'git commit end'